### ISSUE TITLE
Update links.

### ISSUE THREAD

**Issue by octosteve** [learn-co-curriculum/deploy-on-day-1#2]
Page points to a lot of dead links.
Basics points to http://flatironschool.com/program.html
![image](https://cloud.githubusercontent.com/assets/325485/6577283/08361ba4-c713-11e4-9c04-4c183f618654.png)

**Comment by AnnJohn** [comment]
Iceboxing the issue.

**Comment by pletcher** [comment]
Where is this happening? Is it still an issue? @AnnJohn @StevenNunez

**Comment by octosteve** [comment]
https://github.com/learn-co-curriculum/deploy-on-day-1/blob/master/index.html#L40 @pletcher

**Comment by pletcher** [comment]
Ah, thanks :)
