### ISSUE TITLE
add collaborator instructions are confusing

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/deploy-on-day-1#84]
the lab instructs one student to fork and add the other students as collaborators, but they don't have access to add collaborators to forks from learn-co students.  need to come up with a better system for collaborating and include that in the instructions.

**Comment by pletcher** [comment]
Is this still the case? It's because the repo's private, right? (Should the repo be private?)

**Comment by ipc103** [comment]
Yes - I believe all the repos on learn-co-students are private. @SophieDeBenedetto @StevenNunez how did the deploy on day 1 go yesterday?

**Comment by octosteve** [comment]
@ipc103 Seemed to work ok... It's private and they were able to push to each other's forks. Come to think of it... I'm not sure how!

**Comment by pletcher** [comment]
Hminteresting. So everything works now?

**Comment by maxwellbenton** [comment]
Seems like this hasn't been an issue, so I'm going to go ahead and close this.
