### ISSUE TITLE
Instructions on how to merge branches of a fork are a bit off

### ISSUE THREAD

**Issue by jjseymour** [learn-co-curriculum/deploy-on-day-1#85]
The instructions are for merging branches that are not part of a fork. There should be instructions on creating a pull request to the master of the fork (a lot of students were creating a pull request of their branch directly to master of learn-co-students).

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by jjseymour** [comment]
@talum Check to see if the instructions for how to merge branches that are not part of a fork are accurate (we might have fixed and forgot to close the issue)

**Comment by talum** [comment]
@jjseymour yeah these instructions are good!
