### ISSUE TITLE
Group logistics instructions could be a little clearer

### ISSUE THREAD

**Issue by realAndrewCohn** [learn-co-curriculum/deploy-on-day-1#86]
"Everyone at the table should then clone this forked repo."
I think we should be more explicit that students are cloning from the fork––maybe change it to:

Everyone at the table should clone the repo from the fork that **one person** at your table created. Do not clone directly from learn-co-curriculum.

**Comment by maxwellbenton** [comment]
Also included now in the readme, as well!
