### ISSUE TITLE
Individual Instructions could be a little clearer

### ISSUE THREAD

**Issue by realAndrewCohn** [learn-co-curriculum/deploy-on-day-1#87]
The individual instructions regarding checking out a new branch could be a little more explicit. I think adding one extra line should clear things up:

"If you haven't already, switch to the branch you created. To make sure you're where you need to be, type git branch in your terminal. It should return the name of your assigned student emphazised with an asterisk and master. The asterisk indicates which branch you're on. It should **not** be master"

**Comment by maxwellbenton** [comment]
Agreed, @realAndrewCohn. I've incorporated this change into the readme.

...Thank you for contributing to a Learn.co lesson, my friend!
