### ISSUE TITLE
Alumni Links are no longer representative

### ISSUE THREAD

**Issue by rrcobb** [learn-co-curriculum/deploy-on-day-1#93]
/alumni is now a page of alumni stories, so these aren't good examples

**Comment by maxwellbenton** [comment]
@rrcobb - I've swapped out these links. Not sure if instructors still do the merging and creating of index pages for the entire team, but I'm guessing they don't host on the site anymore. I've used an old wayback machine link to show the example index page and created a GIF to show an example profile page (not preserved in wayback)
